apiVersion: v1
kind: Service
metadata:
  name: store-engine-persistence-service
spec:
  selector:
    app: store-engine-persistence-ms
  ports:
    - port: 2999
      targetPort: 2999
  type: NodePort
