apiVersion: v1
kind: Service
metadata:
  name: store-engine-persistence-ms-service
spec:
  selector:
    app: store-engine-persistence-ms
  ports:
    - protocol: TCP
      port: 80
      targetPort: 2999
  type: NodePort
